name: setup-circleci-cli
description: Setup CircleCI CLI, circleci, on GitHub Actions runners
inputs:
  version:
    description: Version of CircleCI CLI to install
    required: false
    default: latest
runs:
  using: node12
  main: dist/index.js
